# Generated by Django 4.0.6 on 2022-07-28 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='actors')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='directors')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='producers')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProductionCompanies',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('running_time', models.DurationField(default='0 0:00:00')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('video_preview', models.FileField(blank=True, null=True, upload_to='videos')),
                ('synopsis', models.TextField()),
                ('background', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('none', 'None'), ('upcoming', 'Upcoming'), ('airing', 'Airing'), ('finishedairing', 'FinishedAiring')], default='none', max_length=50)),
                ('countries_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.CharField(max_length=60)),
                ('avg_rating', models.FloatField(default=0)),
                ('number_rating', models.IntegerField(default=0)),
                ('released_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('directors', models.ManyToManyField(to='myllist_app.director')),
                ('genres', models.ManyToManyField(related_name='genres', to='myllist_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='writers')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('character_role', models.CharField(choices=[('none', 'None'), ('supporting', 'Supporting'), ('main', 'Main')], default='none', max_length=50)),
                ('credit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='myllist_app.actor')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='myllist_app.show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='platforms',
            field=models.ManyToManyField(to='myllist_app.streamingplatform'),
        ),
        migrations.AddField(
            model_name='show',
            name='production_companies',
            field=models.ManyToManyField(to='myllist_app.productioncompany'),
        ),
        migrations.AddField(
            model_name='show',
            name='types',
            field=models.ManyToManyField(to='myllist_app.type'),
        ),
        migrations.AddField(
            model_name='show',
            name='writers',
            field=models.ManyToManyField(to='myllist_app.writer'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(choices=[('none', 'None'), ('plan', 'Plan'), ('watching', 'Watching'), ('completed', 'Completed')], default='none', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myllist_app.show')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('alternative_title', models.CharField(max_length=100)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_titles', to='myllist_app.show')),
            ],
        ),
    ]
