# Generated by Django 4.0.6 on 2022-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0004_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
