# Generated by Django 4.0.6 on 2022-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0007_alter_director_about_alter_productioncompany_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('upcoming', 'Upcoming'), ('airing', 'Airing'), ('finishedairing', 'Finished Airing')], default='none', max_length=50),
        ),
    ]
