# Generated by Django 4.0.6 on 2022-08-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0008_alter_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_backdrop',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
