# Generated by Django 4.0.6 on 2022-08-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0009_show_show_backdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
