# Generated by Django 4.0.6 on 2022-08-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0010_show_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('-released_date',)},
        ),
    ]
