# Generated by Django 4.0.6 on 2022-08-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0011_alter_show_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcharacter',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='myllist_app.show'),
        ),
    ]
