# Generated by Django 4.0.6 on 2022-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0013_alter_review_status_alter_show_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
