# Generated by Django 4.0.6 on 2022-09-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myllist_app', '0015_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('plan', 'Plan'), ('watching', 'Watching'), ('completed', 'Completed')], default='none', max_length=50, null=True),
        ),
    ]
